version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: nuclear_outages
    ports:
      - "6603:3306"  
    volumes:
      - ../src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - my_network

  data-ingestion:
    build:
      context: ../src/data-ingestion
    container_name: data-ingestion-container
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: nuclear_outages
    command: ["python", "app.py"]
    networks:
      - my_network

  api:
    build:
      context: ../src/database-api
    container_name: api-container
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: nuclear_outages
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
